version: '3.1'

services:

  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: task_manager
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
